/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Forest(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/forest.glb')
  return (
    <group ref={group} {...props}>
      <group position={[-5.52, 0.03, -3.17]} scale={[0.63, 0.63, 0.63]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube038_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube038_1.geometry} />
      </group>
      <group position={[-10.76, 0.03, 8.94]} rotation={[0, 0.98, 0]} scale={[0.63, 0.63, 0.63]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube039_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube039_1.geometry} />
      </group>
      <group position={[-28.15, -4.15, 9.27]} rotation={[0.49, -0.8, 0.47]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube040_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube040_1.geometry} />
      </group>
      <group position={[-21.47, -1.73, 15.1]} rotation={[-2.82, -0.06, 2.58]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube041_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube041_1.geometry} />
      </group>
      <group position={[-8.29, 0.01, -2.63]} rotation={[Math.PI, -0.04, Math.PI]} scale={[0.54, 0.54, 0.54]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube042_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube042_1.geometry} />
      </group>
      <group position={[-23.88, -1.96, 11.17]} rotation={[-2.82, -0.06, 2.58]} scale={[0.86, 0.86, 0.86]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube043_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube043_1.geometry} />
      </group>
      <group position={[-25.5, -2.55, -0.87]} rotation={[-2.04, 0.79, 1.71]} scale={[0.86, 0.86, 0.86]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube044_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube044_1.geometry} />
      </group>
      <group position={[-24.95, -3.26, -5.75]} rotation={[2.52, -0.9, 2.46]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube046_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube046_1.geometry} />
      </group>
      <group position={[-10.2, 0.01, -1.49]} rotation={[Math.PI, -0.93, Math.PI]} scale={[0.61, 0.61, 0.61]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube047_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube047_1.geometry} />
      </group>
      <group position={[-6.42, 0.03, 8.51]} rotation={[0, -0.97, 0]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube048_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube048_1.geometry} />
      </group>
      <group position={[-6.05, 0.03, 12.16]} rotation={[Math.PI, -1.42, Math.PI]} scale={[0.75, 0.75, 0.75]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube049_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube049_1.geometry} />
      </group>
      <group position={[-9.95, -0.13, 8.25]} scale={[0.41, 0.41, 0.41]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube050_0.geometry} />
      </group>
      <group position={[-9.32, 0.3, 8.89]} rotation={[0.14, 0.31, -0.23]} scale={[0.41, 0.41, 0.41]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube051_0.geometry} />
      </group>
      <group position={[-8.48, -0.22, 8.44]} rotation={[0.02, 0.23, -0.06]} scale={[0.34, 0.34, 0.34]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube052_0.geometry} />
      </group>
      <group position={[-6.79, -0.22, 1.36]} rotation={[0.02, -0.83, -0.03]} scale={[0.34, 0.34, 0.34]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube053_0.geometry} />
      </group>
      <group position={[-7.6, 0.3, 0.85]} rotation={[0.18, -0.74, -0.06]} scale={[0.41, 0.41, 0.41]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube054_0.geometry} />
      </group>
      <group position={[-7.35, -0.13, -0.02]} rotation={[0, -1.06, 0]} scale={[0.41, 0.41, 0.41]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube055_0.geometry} />
      </group>
      <group position={[-13.19, -0.3, 1.51]} rotation={[2.95, -1.16, -3.12]} scale={[0.41, 0.41, 0.41]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube056_0.geometry} />
      </group>
      <group position={[-14.42, 0.15, 3.99]} rotation={[3.07, -1.4, -2.6]} scale={[0.41, 0.41, 0.41]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube057_0.geometry} />
      </group>
      <group position={[-14.07, -0.04, 4.78]} rotation={[-2.96, -1.41, -3]} scale={[0.34, 0.34, 0.34]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube058_0.geometry} />
      </group>
      <group position={[-13.43, -0.14, 7.48]} rotation={[-0.23, -1.06, -0.02]} scale={[0.33, 0.33, 0.33]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube059_0.geometry} />
      </group>
      <group position={[-1.15, -0.29, 8.24]} rotation={[0.1, -0.99, 0.2]} scale={[0.33, 0.33, 0.33]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube060_0.geometry} />
      </group>
      <group position={[-2.28, -0.03, 7.31]} rotation={[0.43, -0.88, 0.45]} scale={[0.33, 0.44, 0.33]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube061_0.geometry} />
      </group>
      <group position={[-1.51, -0.07, 7.01]} rotation={[0.04, -0.98, 0.03]} scale={[0.37, 0.23, 0.37]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube062_0.geometry} />
      </group>
      <group position={[-1.71, -0.18, 8.07]} rotation={[-0.24, 0.97, 0.21]} scale={[0.33, 0.33, 0.33]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube063_0.geometry} />
      </group>
      <group position={[-0.28, -0.07, -1.16]} rotation={[3.08, -1.2, 3.08]} scale={[0.37, 0.23, 0.37]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube065_0.geometry} />
      </group>
      <group position={[-0.96, -0.03, -1.61]} rotation={[2.42, -1.16, 2.58]} scale={[0.33, 0.44, 0.33]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube066_0.geometry} />
      </group>
      <group position={[-1.08, -0.29, -0.16]} rotation={[2.99, -1.19, 3.12]} scale={[0.33, 0.33, 0.33]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cube067_0.geometry} />
      </group>
      <group position={[3.99, 0.03, -4.72]} rotation={[-Math.PI, 1.04, -Math.PI]} scale={[0.75, 0.75, 0.75]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube068_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube068_1.geometry} />
      </group>
      <group position={[3.15, 0.03, 11.7]} rotation={[Math.PI, -1.02, Math.PI]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube069_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube069_1.geometry} />
      </group>
      <group position={[-0.47, 0.03, -3.11]} rotation={[Math.PI, -1.02, Math.PI]} scale={[0.46, 0.46, 0.46]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube070_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube070_1.geometry} />
      </group>
      <group position={[-1.83, -3.26, -16.09]} rotation={[2.75, 0.31, 3.09]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube071_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube071_1.geometry} />
      </group>
      <group position={[-11.68, -3.71, -16.98]} rotation={[-0.69, 0.51, -0.03]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube072_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube072_1.geometry} />
      </group>
      <group position={[-6.7, -2.55, -15.47]} rotation={[-0.79, 0.5, -0.03]} scale={[0.86, 0.86, 0.86]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube073_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube073_1.geometry} />
      </group>
      <group position={[-18.02, -1.96, -11.05]} rotation={[-2.31, 1.13, 1.78]} scale={[0.86, 0.86, 0.86]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube074_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube074_1.geometry} />
      </group>
      <group position={[-21.26, -1.73, -7.78]} rotation={[-2.31, 1.13, 1.78]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube075_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube075_1.geometry} />
      </group>
      <group position={[-17.18, -4.15, -15.65]} rotation={[2.61, -0.87, 2.83]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube076_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube076_1.geometry} />
      </group>
      <group position={[-3.65, -4.15, 25.68]} rotation={[0.43, 0.67, -0.16]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube077_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube077_1.geometry} />
      </group>
      <group position={[2.15, -1.73, 18.97]} rotation={[-1.37, -1.24, -1.93]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube078_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube078_1.geometry} />
      </group>
      <group position={[-1.76, -1.96, 21.4]} rotation={[-1.37, -1.24, -1.93]} scale={[0.86, 0.86, 0.86]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube079_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube079_1.geometry} />
      </group>
      <group position={[-13.8, -2.55, 23.07]} rotation={[-2.42, -0.33, 2.94]} scale={[0.86, 0.86, 0.86]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube080_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube080_1.geometry} />
      </group>
      <group position={[-9.3, -3.71, 25.69]} rotation={[-2.52, -0.32, 2.96]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube081_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube081_1.geometry} />
      </group>
      <group position={[-18.68, -3.26, 22.54]} rotation={[0.43, -0.53, 0.06]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube082_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube082_1.geometry} />
      </group>
      <group position={[11.49, -3.71, 9.5]} rotation={[-1.35, -0.97, -1.71]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube083_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube083_1.geometry} />
      </group>
      <group position={[7.88, -2.55, 13.24]} rotation={[-1.34, -0.87, -1.76]} scale={[0.86, 0.86, 0.86]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube084_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube084_1.geometry} />
      </group>
      <group position={[9.33, -2.42, -1.97]} rotation={[-0.32, -0.16, -0.63]} scale={[0.86, 0.86, 0.86]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube085_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube085_1.geometry} />
      </group>
      <group position={[7.67, -1.73, -3.23]} rotation={[-0.32, -0.16, -0.63]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube086_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube086_1.geometry} />
      </group>
      <group position={[13.04, -4.6, 0.88]} rotation={[2.5, 1, -2.47]} scale={[0.66, 0.66, 0.66]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube087_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube087_1.geometry} />
      </group>
      <group position={[8.62, -2.55, -9.27]} rotation={[-0.69, -0.16, -0.61]} scale={[0.86, 0.86, 0.86]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube090_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube090_1.geometry} />
      </group>
      <group position={[2.6, -2.72, -13.74]} rotation={[-2.69, -0.93, -2.31]} scale={[0.86, 0.86, 0.86]}>
        <mesh material={materials['Material.002']} geometry={nodes.Cube091_0.geometry} />
        <mesh material={materials['0001']} geometry={nodes.Cube091_1.geometry} />
      </group>
      <group position={[4.08, 5.9, -1.01]} rotation={[-2.5, 1.47, 2.33]} />
      <group position={[1.12, 11.42, -3.44]} rotation={[1.76, 1.19, -2.3]} />
      <group position={[-6.42, -0.01, 4.36]} scale={[9.74, 9.74, 9.74]}>
        <mesh receiveShadow material={materials['Material.005']} geometry={nodes.Plane_0.geometry} />
      </group>
      <group position={[2.46, 0.34, 8.47]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane002_0.geometry} />
      </group>
      <group position={[-17.4, 0.34, 5.52]} rotation={[2.73, -0.44, 1.78]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane004_0.geometry} />
      </group>
      <group position={[3.61, 0.34, 3.03]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane005_0.geometry} />
      </group>
      <group position={[-18.79, 0.34, 7.38]} rotation={[2.68, -0.64, 1.67]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane006_0.geometry} />
      </group>
      <group position={[0.5, 0.22, 10.49]} rotation={[2.54, -1.06, 1.19]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane007_0.geometry} />
      </group>
      <group position={[5.51, 0.34, 9.14]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane008_0.geometry} />
      </group>
      <group position={[6.23, 0.34, 3.54]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane009_0.geometry} />
      </group>
      <group position={[2.22, 0.34, 0.59]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane010_0.geometry} />
      </group>
      <group position={[5.38, 0.34, 0.19]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane011_0.geometry} />
      </group>
      <group position={[8.21, 0.34, 0.71]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane012_0.geometry} />
      </group>
      <group position={[6.23, 0.34, 11.19]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane013_0.geometry} />
      </group>
      <group position={[8.14, 0.34, 12.89]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane014_0.geometry} />
      </group>
      <group position={[-15.24, 0.34, 3.7]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane015_0.geometry} />
      </group>
      <group position={[10.73, 0.34, 1.5]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane016_0.geometry} />
      </group>
      <group position={[-18.24, 0.34, 9.29]} rotation={[0.87, -1.08, -0.37]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane017_0.geometry} />
      </group>
      <group position={[-17.75, 0.34, 13.91]} rotation={[1.31, -1.19, 0.11]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane018_0.geometry} />
      </group>
      <group position={[-19.87, 0.34, 12.46]} rotation={[2.36, -1.03, 1.26]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane019_0.geometry} />
      </group>
      <group position={[-16.02, 0.34, 15.64]} rotation={[1, -1.13, -0.23]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane020_0.geometry} />
      </group>
      <group position={[-13.27, 0.34, 16.31]} rotation={[0.5, -0.72, -0.83]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane021_0.geometry} />
      </group>
      <group position={[-10.07, 0.34, 16.64]} rotation={[0.47, -0.65, -0.88]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane022_0.geometry} />
      </group>
      <group position={[-4.03, 0.34, 17.93]} rotation={[0.47, -0.65, -0.88]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane023_0.geometry} />
      </group>
      <group position={[-7.22, 0.34, 17.6]} rotation={[0.5, -0.72, -0.83]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane024_0.geometry} />
      </group>
      <group position={[-1.09, 0.34, 18.68]} rotation={[0.5, -0.72, -0.83]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane025_0.geometry} />
      </group>
      <group position={[-1.39, 0.34, 14.31]} rotation={[0.47, -0.65, -0.88]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane026_0.geometry} />
      </group>
      <group position={[-0.4, 0.34, 12.28]} rotation={[0.47, -0.65, -0.88]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane027_0.geometry} />
      </group>
      <group position={[1.75, 0.34, 13.68]} rotation={[0.47, -0.65, -0.88]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane028_0.geometry} />
      </group>
      <group position={[1.62, 0.34, 16.18]} rotation={[0.4, 0.39, -1.34]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane029_0.geometry} />
      </group>
      <group position={[-4.08, 0.34, -2.26]} rotation={[2.77, -0.05, 1.94]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane030_0.geometry} />
      </group>
      <group position={[0.36, 0.34, -2.26]} rotation={[2.77, -0.05, 1.94]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane031_0.geometry} />
      </group>
      <group position={[-13.53, 0.34, 0.03]} rotation={[2.77, -0.05, 1.94]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane032_0.geometry} />
      </group>
      <group position={[-10.65, 0.34, 0.29]} rotation={[2.77, -0.05, 1.94]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane033_0.geometry} />
      </group>
      <group position={[-12.99, 0.34, -2.47]} rotation={[2.77, -0.05, 1.94]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane034_0.geometry} />
      </group>
      <group position={[6.23, 0.34, 6.34]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane035_0.geometry} />
      </group>
      <group position={[3.31, 0.34, 6.34]} rotation={[2.32, -1.06, 1.21]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane036_0.geometry} />
      </group>
      <group position={[-7.17, 0.34, -1.05]} rotation={[2.77, -0.05, 1.94]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Plane037_0.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/forest.glb')
