/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function ForestSimple(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/forest-simple.glb')
  return (
    <group ref={group} {...props}>
      <group position={[4.08, 5.9, -1.01]} rotation={[-2.5, 1.47, 2.33]} />
      <group position={[1.12, 11.42, -3.44]} rotation={[1.76, 1.19, -2.3]} />
      <group position={[-6.42, -0.01, 4.36]} scale={[9.74, 9.74, 9.74]}>
        <mesh receiveShadow material={materials['Material.005']} geometry={nodes.Plane_0.geometry} />
      </group>
      <group position={[-1.39, 0.34, 14.31]} rotation={[0.47, -0.65, -0.88]} scale={[0.83, 0.83, 0.83]}>
        <mesh material={materials['Material.008']} geometry={nodes.Grass001.geometry} />
      </group>
      <group position={[-9.32, 0.3, 8.89]} rotation={[0.14, 0.31, -0.23]} scale={[0.41, 0.41, 0.41]}>
        <mesh castShadow material={materials['Material.004']} geometry={nodes.Rocks001.geometry} />
      </group>
      <group position={[-0.47, 0.03, -3.11]} rotation={[Math.PI, -1.02, Math.PI]} scale={[0.46, 0.46, 0.46]}>
        <mesh castShadow material={materials['0001']} geometry={nodes.Leaves.geometry} />
        <mesh castShadow material={materials['Material.002']} geometry={nodes.Trunks.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/forest-simple.glb')
