/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Lowpoly(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lowpoly.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh receiveShadow 
        material={materials.Material}
        geometry={nodes.Scene_1.geometry}
        position={[4.49, 0.5, 0]}
        rotation={[Math.PI, -1.2, Math.PI]}
        scale={[1.95, 1.95, 1.95]}
      />
    </group>
  )
}

useGLTF.preload('/lowpoly.glb')
